# =============================================================================
# Secrets Manager Module — ProtegoPay
# =============================================================================
# Creates AWS Secrets Manager secrets for all application credentials.
# Secret VALUES are never stored in Terraform state as plaintext — they are
# populated after initial provisioning via a separate rotation workflow or
# manual CLI command.
#
# Secrets created:
#   - DB_URL               PostgreSQL connection string
#   - REDIS_URL            Redis connection string with auth token
#   - JWT_SECRET           JWT signing key (HS256/RS256)
#   - WEBHOOK_HMAC_SECRET  HMAC-SHA256 key for concessionaire webhook validation
#
# IMPORTANT: Terraform only creates the secret CONTAINERS here.
# Initial values are set via:
#   aws secretsmanager put-secret-value \
#     --secret-id <arn> \
#     --secret-string '{"value":"<actual-secret>"}'
# This ensures no secret values appear in Terraform state, plan output,
# or CI logs.
# =============================================================================

data "aws_caller_identity" "current" {}
data "aws_region" "current" {}

# ---------------------------------------------------------------------------
# KMS Key for Secrets Manager encryption
# ---------------------------------------------------------------------------

resource "aws_kms_key" "secrets" {
  description             = "${var.project_name} ${var.environment} secrets manager key"
  deletion_window_in_days = 30
  enable_key_rotation     = true

  tags = {
    Name = "${var.project_name}-${var.environment}-secrets-kms"
  }
}

resource "aws_kms_alias" "secrets" {
  name          = "alias/${var.project_name}-${var.environment}-secrets"
  target_key_id = aws_kms_key.secrets.key_id
}

# ---------------------------------------------------------------------------
# Helper: IAM policy document for secret resource policy
# ---------------------------------------------------------------------------

locals {
  secret_names = {
    db_url              = "${var.project_name}/${var.environment}/DB_URL"
    redis_url           = "${var.project_name}/${var.environment}/REDIS_URL"
    jwt_secret          = "${var.project_name}/${var.environment}/JWT_SECRET"
    webhook_hmac_secret = "${var.project_name}/${var.environment}/WEBHOOK_HMAC_SECRET"
  }
}

# ---------------------------------------------------------------------------
# DB_URL Secret
# ---------------------------------------------------------------------------

resource "aws_secretsmanager_secret" "db_url" {
  name                    = local.secret_names.db_url
  description             = "${var.project_name} ${var.environment} — PostgreSQL connection string. Value set post-provisioning."
  kms_key_id              = aws_kms_key.secrets.arn
  recovery_window_in_days = var.recovery_window_days

  tags = {
    Name        = "${var.project_name}-${var.environment}-db-url"
    SecretType  = "database-credentials"
    Environment = var.environment
  }
}

resource "aws_secretsmanager_secret_version" "db_url_placeholder" {
  secret_id = aws_secretsmanager_secret.db_url.id
  # Placeholder value — replace immediately after provisioning with the real
  # DB_URL constructed from RDS endpoint + master credentials.
  # The actual password is generated by the rds module and passed in here.
  secret_string = jsonencode({
    placeholder = "REPLACE_AFTER_PROVISIONING"
    host        = var.db_host
    port        = "5432"
    database    = var.db_name
    username    = var.db_username
    # password is intentionally omitted here — set via rotation lambda or CLI
  })

  lifecycle {
    ignore_changes = [
      secret_string # Managed outside Terraform after initial deploy
    ]
  }
}

# ---------------------------------------------------------------------------
# REDIS_URL Secret
# ---------------------------------------------------------------------------

resource "aws_secretsmanager_secret" "redis_url" {
  name                    = local.secret_names.redis_url
  description             = "${var.project_name} ${var.environment} — Redis connection URL. Value set post-provisioning."
  kms_key_id              = aws_kms_key.secrets.arn
  recovery_window_in_days = var.recovery_window_days

  tags = {
    Name        = "${var.project_name}-${var.environment}-redis-url"
    SecretType  = "cache-credentials"
    Environment = var.environment
  }
}

resource "aws_secretsmanager_secret_version" "redis_url_placeholder" {
  secret_id = aws_secretsmanager_secret.redis_url.id
  secret_string = jsonencode({
    placeholder = "REPLACE_AFTER_PROVISIONING"
    host        = var.redis_host
    port        = tostring(var.redis_port)
    # auth_token is intentionally omitted — set via rotation lambda or CLI
  })

  lifecycle {
    ignore_changes = [
      secret_string
    ]
  }
}

# ---------------------------------------------------------------------------
# JWT_SECRET
# ---------------------------------------------------------------------------

resource "aws_secretsmanager_secret" "jwt_secret" {
  name                    = local.secret_names.jwt_secret
  description             = "${var.project_name} ${var.environment} — JWT signing secret. Rotated every 90 days."
  kms_key_id              = aws_kms_key.secrets.arn
  recovery_window_in_days = var.recovery_window_days

  tags = {
    Name        = "${var.project_name}-${var.environment}-jwt-secret"
    SecretType  = "signing-key"
    Environment = var.environment
  }
}

resource "aws_secretsmanager_secret_version" "jwt_secret_placeholder" {
  secret_id     = aws_secretsmanager_secret.jwt_secret.id
  secret_string = jsonencode({ placeholder = "REPLACE_AFTER_PROVISIONING" })

  lifecycle {
    ignore_changes = [
      secret_string
    ]
  }
}

# ---------------------------------------------------------------------------
# WEBHOOK_HMAC_SECRET
# ---------------------------------------------------------------------------

resource "aws_secretsmanager_secret" "webhook_hmac_secret" {
  name                    = local.secret_names.webhook_hmac_secret
  description             = "${var.project_name} ${var.environment} — HMAC-SHA256 key for concessionaire webhook validation."
  kms_key_id              = aws_kms_key.secrets.arn
  recovery_window_in_days = var.recovery_window_days

  tags = {
    Name        = "${var.project_name}-${var.environment}-webhook-hmac"
    SecretType  = "signing-key"
    Environment = var.environment
  }
}

resource "aws_secretsmanager_secret_version" "webhook_hmac_placeholder" {
  secret_id     = aws_secretsmanager_secret.webhook_hmac_secret.id
  secret_string = jsonencode({ placeholder = "REPLACE_AFTER_PROVISIONING" })

  lifecycle {
    ignore_changes = [
      secret_string
    ]
  }
}

# ---------------------------------------------------------------------------
# IAM Policy — application can read these secrets
# ---------------------------------------------------------------------------

resource "aws_iam_policy" "read_app_secrets" {
  name        = "${var.project_name}-${var.environment}-read-app-secrets"
  description = "Allows the application role to read ${var.project_name} ${var.environment} secrets from Secrets Manager."

  policy = jsonencode({
    Version = "2012-10-17"
    Statement = [
      {
        Sid    = "ReadAppSecrets"
        Effect = "Allow"
        Action = [
          "secretsmanager:GetSecretValue",
          "secretsmanager:DescribeSecret"
        ]
        Resource = [
          aws_secretsmanager_secret.db_url.arn,
          aws_secretsmanager_secret.redis_url.arn,
          aws_secretsmanager_secret.jwt_secret.arn,
          aws_secretsmanager_secret.webhook_hmac_secret.arn,
        ]
      },
      {
        Sid    = "DecryptSecretsKMS"
        Effect = "Allow"
        Action = [
          "kms:Decrypt",
          "kms:DescribeKey"
        ]
        Resource = aws_kms_key.secrets.arn
      }
    ]
  })

  tags = {
    Name = "${var.project_name}-${var.environment}-read-app-secrets-policy"
  }
}
